<a href="https://colab.research.google.com/github/miriam-silva/TarefaETL-Mineiracao/blob/main/Tarefa_ETL(16_09).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# FASE 1 - EXTRAÇÃO/DIAGNÓSTICO

In [3]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import files
uploaded = files.upload()

Saving fundamentadas-atendidas-2025.csv to fundamentadas-atendidas-2025.csv

In [7]:
df = pd.read_csv(
    "fundamentadas-atendidas-2025.csv",
    encoding="latin1",
    sep=";"
)

df.head()

,Unidade de Atendimento,FA,FA Antiga,Tipo de Atendimento,Status Reclamação,Baixa da Reclamacao,Área,Assunto,Problema,Consumidor,Data Cadastro Reclamação,Data Reclamação Baixada,Data Reclamação Arquivada,Total
0,Procon Fortaleza,23-002.001.24-0043898,NaN,Retorno da CIP,Reclamação arquivada,Fundamentada Atendida,Produtos,Geladeira e Freezer,Defeito/Risco à saúde e segurança,LUCIANA DE CARVALHO,02-01-2025 08:15:02,21-02-2025 12:14:36,21-02-2025 12:14:36,1
1,Procon Fortaleza,23-002.001.24-0043846,NaN,Retorno da CIP,Reclamação arquivada,Fundamentada Não Atendida,Assuntos Financeiros,Outros Contratos,Cobrança indevida.,CARLOS ALBERTO DA SILVA,02-01-2025 08:26:58,15-04-2025 09:26:29,15-04-2025 09:26:29,1
2,Procon Fortaleza,23-002.001.24-0043851,NaN,Retorno da CIP,Reclamação arquivada,Fundamentada Não Atendida,Assuntos Financeiros,Outros Contratos,Calculo de prestação/taxa de juros,MARIA DALVA MENEZES ABRANTES,02-01-2025 08:39:06,21-02-2025 10:37:15,21-02-2025 10:37:15,1
3,Procon Fortaleza,23-002.001.24-0043862,NaN,Retorno da CIP,Reclamação arquivada,Não Fundamentada/Encerrada,Assuntos Financeiros,Seguro,"Contrato (não cumprimento, alteração, transfer...",GILDAZIO OLIVEIRA DOS SANTOS,02-01-2025 08:48:50,22-04-2025 11:03:46,22-04-2025 11:03:46,1
4,Procon Fortaleza Núcleo Vapt Vupt Messejana,23-002.004.24-0043430,NaN,Retorno da CIP,Reclamação arquivada,Fundamentada Não Atendida,Assuntos Financeiros,Cartão de Crédito,Consumidor negativado indevidamente nos serviç...,BEATRIZ PEREIRA MARINHO,02-01-2025 08:50:07,18-06-2025 12:22:25,18-06-2025 12:22:25,1

In [8]:
print("Quantidade de registros:", df.shape[0])
print("Quantidade de colunas:", df.shape[1])

Quantidade de registros: 6806
Quantidade de colunas: 14

In [9]:
print("Colunas da base:")
for coluna in df.columns:
    print("-", coluna)

Colunas da base:
- Unidade de Atendimento
- FA
- FA Antiga
- Tipo de Atendimento
- Status Reclamação
- Baixa da Reclamacao
- Área
- Assunto
- Problema
- Consumidor
- Data Cadastro Reclamação
- Data Reclamação Baixada
- Data Reclamação Arquivada
- Total

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6806 entries, 0 to 6805
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Unidade de Atendimento     6806 non-null   object
 1   FA                         6806 non-null   object
 2   FA Antiga                  0 non-null      float64
 3   Tipo de Atendimento        6806 non-null   object
 4   Status Reclamação          6806 non-null   object
 5   Baixa da Reclamacao        6806 non-null   object
 6   Área                       6806 non-null   object
 7   Assunto                    6806 non-null   object
 8   Problema                   6806 non-null   object
 9   Consumidor                 6806 non-null   object
 10  Data Cadastro Reclamação   6806 non-null   object
 11  Data Reclamação Baixada    6453 non-null   object
 12  Data Reclamação Arquivada  6453 non-null   object
 13  Total                      6806 non-null   int64
dtypes: float64(1), int64(1), object(12)
memory usage: 744.5+ KB

In [12]:
df.isnull().sum()

Unidade de Atendimento          0
FA                              0
FA Antiga                    6806
Tipo de Atendimento             0
Status Reclamação               0
Baixa da Reclamacao             0
Área                            0
Assunto                         0
Problema                        0
Consumidor                      0
Data Cadastro Reclamação        0
Data Reclamação Baixada       353
Data Reclamação Arquivada     353
Total                           0
dtype: int64

In [13]:
nulos = df.isnull().sum()

percentual_nulos = (nulos / len(df)) * 100

diagnostico_nulos = pd.DataFrame({
    "Valores Ausentes": nulos,
    "Percentual (%)": percentual_nulos.round(2)
})

diagnostico_nulos

                           Valores Ausentes  Percentual (%)
Unidade de Atendimento                    0            0.00
FA                                        0            0.00
FA Antiga                              6806          100.00
Tipo de Atendimento                       0            0.00
Status Reclamação                         0            0.00
Baixa da Reclamacao                       0            0.00
Área                                      0            0.00
Assunto                                   0            0.00
Problema                                  0            0.00
Consumidor                                0            0.00
Data Cadastro Reclamação                  0            0.00
Data Reclamação Baixada                 353            5.19
Data Reclamação Arquivada               353            5.19
Total                                     0            0.00

In [14]:
duplicados = df.duplicated().sum()

print("Quantidade de registros duplicados:", duplicados)

Quantidade de registros duplicados: 0

In [15]:
df.dtypes

Unidade de Atendimento        object
FA                            object
FA Antiga                    float64
Tipo de Atendimento           object
Status Reclamação             object
Baixa da Reclamacao           object
Área                          object
Assunto                       object
Problema                      object
Consumidor                    object
Data Cadastro Reclamação      object
Data Reclamação Baixada       object
Data Reclamação Arquivada     object
Total                          int64
dtype: object

In [17]:
df["Status Reclamação"].value_counts(dropna=False)
df["Baixa da Reclamacao"].value_counts(dropna=False)
df["Área"].value_counts(dropna=False)
df["Unidade de Atendimento"].value_counts(dropna=False)

Unidade de Atendimento
Procon Fortaleza                                     3921
Procon Fortaleza Núcleo Vapt Vupt Messejana          1023
Procon Fortaleza Núcleo Vapt Vupt Antônio Bezerra     707
Procon Fortaleza Núcleo Vapt Vupt Centro              403
Procon Fortaleza Núcleo Vapt Vupt Parangaba           337
Procon Fortaleza Núcleo Vapt Vupt Rio Mar Papicu      214
Procon Fortaleza - Núcleo Câmara Municipal            112
Procon Fortaleza - Núcleo Regional 5                   44
Procon Fortaleza - Núcleo Regional 6                   33
Procon Fortaleza Audiência Virtual                     12
Name: count, dtype: int64

In [18]:
df["Total"].value_counts(dropna=False)
df["Total"].describe()

count    6806.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0
Name: Total, dtype: float64

In [19]:
df["Data Cadastro Reclamação"].head(10)
df["Data Reclamação Baixada"].head(10)
df["Data Reclamação Arquivada"].head(10)

0    21-02-2025 12:14:36
1    15-04-2025 09:26:29
2    21-02-2025 10:37:15
3    22-04-2025 11:03:46
4    18-06-2025 12:22:25
5    21-02-2025 09:48:58
6    21-02-2025 11:11:29
7    24-02-2025 11:43:37
8    19-02-2025 14:25:29
9    14-02-2025 16:42:05
Name: Data Reclamação Arquivada, dtype: object

In [20]:
print(df["Problema"].unique()[:30])
print(df["Assunto"].unique()[:30])

['Defeito/Risco à saúde e segurança' 'Cobrança indevida.'
 'Calculo de prestação/taxa de juros'
 'Contrato (não cumprimento, alteração, transferencia, irregularidade, rescisão, etc.)'
 'Consumidor negativado indevidamente nos serviços de proteção ao credito'
 'Cobrança indevida/abusiva'
 'Demora na montagem/montagem incompleta/incorreta' 'Produto com vício'
 'SAC - Resolução de demandas (ausência de resposta, excesso de prazo, não suspensão imediata da cobrança)'
 'Venda enganosa' 'Produto entregue diferente do pedido'
 'SAC - Acompanhamento de demandas (ausência de registro numérico, não envio do histórico/registro)'
 'Compra de veiculo (multa, transferência, alienação, não entrega de documentação)'
 'Vicio de qualidade (mal executado, inadequado, impróprio)'
 'Calculo de prestação em atraso'
 'SAC - Cancelamento de serviço (retenção, demora, não envio do comprovante)'
 'Roubo de cartão' 'Não entrega/demora na entrega do produto'
 'Crédito Consignado' 'TOI - Termo de Ocorrência de Irregularidade'
 'Garantia - Descumprimento, prazo' 'Lançamento Não Reconhecido na Fatura'
 'Não cumprimento à oferta' 'Cobrança vexatória/difamatória'
 'Venda/Oferta/publicidade enganosa.'
 'Duvida sobre cobrança/valor/reajuste/contrato/orçamento.'
 'Desistência de consorcio'
 'Falha bancaria em transações eletrônicas (transferencias indevidas, saques indevidos)'
 'Dano material/pessoal decorrente do serviço' 'Venda casada']
['Geladeira e Freezer' 'Outros Contratos' 'Seguro' 'Cartão de Crédito'
 'Telefonia Celular' 'Água / Esgoto'
 'Artigo de Cozinha ( Coifa, Exaustor, Panela, Talher, Filtro de Café, Porta-Filtro, Louças, Etc. )'
 'Eletrodoméstico Importado' 'Plano de saúde regulamentado'
 'Telefone ( Convencional, Celular, Interfone, Etc. )'
 'Acessório para Aparelho Eletrônico/Pilha/Elétrico (Agulha, fone de ouvido, bateria, etc.)'
 'Produto de Uso Pessoal ( Barbeador, Depilador, Secador, Outros )'
 'Estabelecimento / Loja - Compra a Prazo' 'Móveis Para Quarto'
 'Energia Elétrica' 'Carro Usado'
 'Telefonia Fixa ( Plano de Expansão / Compra e Venda / Locação )'
 'Banco comercial'
 'Outros Profissionais Liberais ( Esteticista / Massagista / Farmacêutico )'
 'Móveis Para Banheiro'
 'Eletroportáteis ( Batedeira, Liqüidificador, Espremedor de Frutas, Etc. )'
 'Financeira' 'Colchão' 'Óticas ( Lentes / Óculos )'
 'Máquina de Lavar Roupa / Louça e Secadora' 'Serviços Postais'
 'Consórcio Imobiliário' 'Academia de Ginástica / Natação / Esportes'
 'Banco de Dados ( SPC - SERASA - ETC. )'
 'Artigo de Leitura ( Formal, Jornal, Revista, Folheto, Livros, Etc. )']

# FASE 2 — TRANSFORMAÇÃO

In [21]:
df.columns = df.columns.str.strip()

print("Colunas após a limpeza:")
for coluna in df.columns:
    print("-", coluna)

Colunas após a limpeza:
- Unidade de Atendimento
- FA
- FA Antiga
- Tipo de Atendimento
- Status Reclamação
- Baixa da Reclamacao
- Área
- Assunto
- Problema
- Consumidor
- Data Cadastro Reclamação
- Data Reclamação Baixada
- Data Reclamação Arquivada
- Total

In [22]:
print("Colunas antes da transformação:")
print(df.columns.tolist())

df = df.drop(columns=["FA Antiga"])

print("\nColunas depois da transformação:")
print(df.columns.tolist())

Colunas antes da transformação:
['Unidade de Atendimento', 'FA', 'FA Antiga', 'Tipo de Atendimento', 'Status Reclamação', 'Baixa da Reclamacao', 'Área', 'Assunto', 'Problema', 'Consumidor', 'Data Cadastro Reclamação', 'Data Reclamação Baixada', 'Data Reclamação Arquivada', 'Total']

Colunas depois da transformação:
['Unidade de Atendimento', 'FA', 'Tipo de Atendimento', 'Status Reclamação', 'Baixa da Reclamacao', 'Área', 'Assunto', 'Problema', 'Consumidor', 'Data Cadastro Reclamação', 'Data Reclamação Baixada', 'Data Reclamação Arquivada', 'Total']

In [23]:
print("Quantidade de colunas após a transformação:", df.shape[1])

Quantidade de colunas após a transformação: 13

In [24]:
print("Registros sem Data Reclamação Baixada:")
display(
    df[df["Data Reclamação Baixada"].isna()]
    ["Status Reclamação"]
    .value_counts(dropna=False)
)

Registros sem Data Reclamação Baixada:

Status Reclamação
Reclamação em Andamento    353
Name: count, dtype: int64

In [25]:
print("Registros sem Data Reclamação Arquivada:")
display(
    df[df["Data Reclamação Arquivada"].isna()]
    ["Status Reclamação"]
    .value_counts(dropna=False)
)

Registros sem Data Reclamação Arquivada:

Status Reclamação
Reclamação em Andamento    353
Name: count, dtype: int64

In [26]:
colunas_data = [
    "Data Cadastro Reclamação",
    "Data Reclamação Baixada",
    "Data Reclamação Arquivada"
]

for coluna in colunas_data:
    df[coluna] = pd.to_datetime(
        df[coluna],
        format="%d-%m-%Y %H:%M:%S",
        errors="coerce"
    )

display(df.dtypes)

Unidade de Atendimento               object
FA                                   object
Tipo de Atendimento                  object
Status Reclamação                    object
Baixa da Reclamacao                  object
Área                                 object
Assunto                              object
Problema                             object
Consumidor                           object
Data Cadastro Reclamação     datetime64[ns]
Data Reclamação Baixada      datetime64[ns]
Data Reclamação Arquivada    datetime64[ns]
Total                                 int64
dtype: object

In [27]:
for coluna in colunas_data:
    print("\n", coluna)
    print("Valores ausentes:", df[coluna].isna().sum())
    print("Primeiros valores:")
    display(df[coluna].head())

 Data Cadastro Reclamação
Valores ausentes: 0
Primeiros valores:

0   2025-01-02 08:15:02
1   2025-01-02 08:26:58
2   2025-01-02 08:39:06
3   2025-01-02 08:48:50
4   2025-01-02 08:50:07
Name: Data Cadastro Reclamação, dtype: datetime64[ns]

 Data Reclamação Baixada
Valores ausentes: 353
Primeiros valores:

0   2025-02-21 12:14:36
1   2025-04-15 09:26:29
2   2025-02-21 10:37:15
3   2025-04-22 11:03:46
4   2025-06-18 12:22:25
Name: Data Reclamação Baixada, dtype: datetime64[ns]

 Data Reclamação Arquivada
Valores ausentes: 353
Primeiros valores:

0   2025-02-21 12:14:36
1   2025-04-15 09:26:29
2   2025-02-21 10:37:15
3   2025-04-22 11:03:46
4   2025-06-18 12:22:25
Name: Data Reclamação Arquivada, dtype: datetime64[ns]

In [28]:
print("Quantidade de valores duplicados na coluna FA:")

print(df["FA"].duplicated().sum())

Quantidade de valores duplicados na coluna FA:
0

In [29]:
print("Quantidade de valores únicos na coluna FA:")

print(df["FA"].nunique())

print("\nQuantidade total de registros:")

print(len(df))

Quantidade de valores únicos na coluna FA:
6806

Quantidade total de registros:
6806

In [30]:
colunas_texto = df.select_dtypes(include="object").columns

for coluna in colunas_texto:
    vazios = df[coluna].astype(str).str.strip().eq("").sum()
    print(f"{coluna}: {vazios} valores vazios")

Unidade de Atendimento: 0 valores vazios
FA: 0 valores vazios
Tipo de Atendimento: 0 valores vazios
Status Reclamação: 0 valores vazios
Baixa da Reclamacao: 0 valores vazios
Área: 0 valores vazios
Assunto: 0 valores vazios
Problema: 0 valores vazios
Consumidor: 0 valores vazios

In [31]:
print("Valores de Status Reclamação:")

display(
    df["Status Reclamação"].value_counts(dropna=False)
)

Valores de Status Reclamação:

Status Reclamação
Reclamação arquivada       6453
Reclamação em Andamento     353
Name: count, dtype: int64

In [32]:
print("Valores de Baixa da Reclamacao:")

display(
    df["Baixa da Reclamacao"].value_counts(dropna=False)
)

Valores de Baixa da Reclamacao:

Baixa da Reclamacao
Fundamentada Não Atendida     3874
Fundamentada Atendida         1574
Não Fundamentada/Encerrada    1059
Pendente                       297
Consulta Fornecida               2
Name: count, dtype: int64

In [33]:
print("Relação entre Status Reclamação e Baixa da Reclamacao:")

display(
    pd.crosstab(
        df["Status Reclamação"],
        df["Baixa da Reclamacao"]
    )
)

Relação entre Status Reclamação e Baixa da Reclamacao:

Baixa da Reclamacao,Consulta Fornecida,Fundamentada Atendida,Fundamentada Não Atendida,Não Fundamentada/Encerrada,Pendente
Status Reclamação,,,,,
Reclamação arquivada,2,1559,3839,1053,0
Reclamação em Andamento,0,15,35,6,297

In [34]:
casos_atencao = df[
    (df["Status Reclamação"] == "Reclamação em Andamento") &
    (df["Baixa da Reclamacao"] != "Pendente")
]

print("Quantidade de casos para investigação:", len(casos_atencao))

display(
    casos_atencao[
        [
            "FA",
            "Status Reclamação",
            "Baixa da Reclamacao",
            "Data Reclamação Baixada",
            "Data Reclamação Arquivada"
        ]
    ].head(20)
)

Quantidade de casos para investigação: 56

,FA,Status Reclamação,Baixa da Reclamacao,Data Reclamação Baixada,Data Reclamação Arquivada
106,23-002.001.24-0044032,Reclamação em Andamento,Fundamentada Atendida,NaT,NaT
290,23-002.001.24-0042648,Reclamação em Andamento,Fundamentada Atendida,NaT,NaT
304,23-002.001.24-0044615,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT
560,23-002.001.25-0000250,Reclamação em Andamento,Não Fundamentada/Encerrada,NaT,NaT
607,23-002.006.24-0044576,Reclamação em Andamento,Fundamentada Atendida,NaT,NaT
725,23-002.001.25-0000792,Reclamação em Andamento,Não Fundamentada/Encerrada,NaT,NaT
863,23-002.003.25-0001403,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT
1065,23-002.006.25-0002035,Reclamação em Andamento,Não Fundamentada/Encerrada,NaT,NaT
1087,23-002.001.25-0001585,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT
1144,23-002.001.25-0001893,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT
1290,23-002.001.25-0002385,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT
1343,23-002.011.25-0001806,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT
1533,23-002.004.25-0002631,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT
1623,23-002.001.25-0002878,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT
1758,23-002.001.25-0003425,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT
1954,23-002.001.25-0003694,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT
2240,23-002.001.25-0006697,Reclamação em Andamento,Fundamentada Atendida,NaT,NaT
2603,23-002.001.25-0007799,Reclamação em Andamento,Fundamentada Atendida,NaT,NaT
2637,23-002.001.25-0005810,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT
2654,23-002.004.25-0005604,Reclamação em Andamento,Fundamentada Não Atendida,NaT,NaT

In [35]:
print("Valores de Área:")

display(
    df["Área"].value_counts(dropna=False)
)

Valores de Área:

Área
Assuntos Financeiros    3653
Serviços Essenciais     1229
Produtos                 993
Serviços Privados        502
Saúde                    358
Habitação                 55
Alimentos                 16
Name: count, dtype: int64

In [36]:
print("Valores de Tipo de Atendimento:")

display(
    df["Tipo de Atendimento"].value_counts(dropna=False)
)

Valores de Tipo de Atendimento:

Tipo de Atendimento
Retorno da CIP                   5675
Abertura Direta da Reclamação    1127
Encaminhamento a Fiscalização       4
Name: count, dtype: int64

In [37]:
print("Valores de Consumidor:")

display(
    df["Consumidor"].value_counts(dropna=False)
)

Valores de Consumidor:

Consumidor
FRANCISCO MONTE PINTO                     8
MARIA ZENEIDE FREIRE CAVALCANTE           8
LIDUINA MARIA FERNANDES BEZERRA           8
MARIA DOS SANTOS FERREIRA                 8
RAIMUNDO BRITO DA SILVA                   6
                                         ..
ADEMAR MACHADO BARROS                     1
ZILAH OLIVEIRA DE FARIAS                  1
FRANCISCA ALDINEIDE SIMPLICIO DA SILVA    1
LUZIA MARIA LUCIANO                       1
RENATA HINGRYD SARAIVA RAMOS              1
Name: count, Length: 5972, dtype: int64

In [38]:
colunas_categoricas = [
    "Unidade de Atendimento",
    "Tipo de Atendimento",
    "Status Reclamação",
    "Baixa da Reclamacao",
    "Área"
]

for coluna in colunas_categoricas:
    valores_originais = df[coluna].nunique()

    valores_padronizados = (
        df[coluna]
        .astype(str)
        .str.strip()
        .str.lower()
        .nunique()
    )

    print(f"{coluna}:")
    print("  Valores únicos originais:", valores_originais)
    print("  Após padronização:", valores_padronizados)
    print()

Unidade de Atendimento:
  Valores únicos originais: 10
  Após padronização: 10

Tipo de Atendimento:
  Valores únicos originais: 3
  Após padronização: 3

Status Reclamação:
  Valores únicos originais: 2
  Após padronização: 2

Baixa da Reclamacao:
  Valores únicos originais: 5
  Após padronização: 5

Área:
  Valores únicos originais: 7
  Após padronização: 7

In [39]:
print("Valores da coluna Total:")

display(
    df["Total"].value_counts(dropna=False)
)

Valores da coluna Total:

Total
1    6806
Name: count, dtype: int64

In [40]:
print("Quantidade de valores diferentes em Total:", df["Total"].nunique())
print("Valor mínimo:", df["Total"].min())
print("Valor máximo:", df["Total"].max())

Quantidade de valores diferentes em Total: 1
Valor mínimo: 1
Valor máximo: 1

In [41]:
df = df.drop(columns=["Total"])

print("Colunas após a remoção:")
print(df.columns.tolist())

print("\nQuantidade de registros:", len(df))
print("Quantidade de colunas:", len(df.columns))

Colunas após a remoção:
['Unidade de Atendimento', 'FA', 'Tipo de Atendimento', 'Status Reclamação', 'Baixa da Reclamacao', 'Área', 'Assunto', 'Problema', 'Consumidor', 'Data Cadastro Reclamação', 'Data Reclamação Baixada', 'Data Reclamação Arquivada']

Quantidade de registros: 6806
Quantidade de colunas: 12

In [42]:
for coluna in colunas_data:
    print(f"\n{coluna}")
    print("Menor data:", df[coluna].min())
    print("Maior data:", df[coluna].max())

Data Cadastro Reclamação
Menor data: 2025-01-02 08:15:02
Maior data: 2025-12-30 16:24:43

Data Reclamação Baixada
Menor data: 2025-01-21 10:59:13
Maior data: 2026-07-20 11:28:47

Data Reclamação Arquivada
Menor data: 2025-01-21 10:59:13
Maior data: 2026-07-20 11:28:47

In [43]:
for coluna in ["Data Reclamação Baixada", "Data Reclamação Arquivada"]:
    quantidade_2026 = (df[coluna].dt.year == 2026).sum()

    print(f"{coluna}:")
    print("Quantidade de registros em 2026:", quantidade_2026)

Data Reclamação Baixada:
Quantidade de registros em 2026: 825
Data Reclamação Arquivada:
Quantidade de registros em 2026: 825

In [44]:
casos_2026 = df[
    (df["Data Reclamação Baixada"].dt.year == 2026)
]

print("Registros com baixa em 2026:", len(casos_2026))

print("\nAno do cadastro desses registros:")
print(casos_2026["Data Cadastro Reclamação"].dt.year.value_counts())

print("\nStatus desses registros:")
print(casos_2026["Status Reclamação"].value_counts())

Registros com baixa em 2026: 825

Ano do cadastro desses registros:
Data Cadastro Reclamação
2025    825
Name: count, dtype: int64

Status desses registros:
Status Reclamação
Reclamação arquivada    825
Name: count, dtype: int64

In [45]:
inconsistencias_baixa = df[
    df["Data Reclamação Baixada"].notna() &
    (df["Data Reclamação Baixada"] < df["Data Cadastro Reclamação"])
]

print("Registros com baixa anterior ao cadastro:", len(inconsistencias_baixa))

Registros com baixa anterior ao cadastro: 0

In [46]:
inconsistencias_arquivamento = df[
    df["Data Reclamação Arquivada"].notna() &
    (df["Data Reclamação Arquivada"] < df["Data Cadastro Reclamação"])
]

print("Registros com arquivamento anterior ao cadastro:", len(inconsistencias_arquivamento))

Registros com arquivamento anterior ao cadastro: 0

In [47]:
inconsistencias_datas = df[
    df["Data Reclamação Baixada"].notna() &
    df["Data Reclamação Arquivada"].notna() &
    (df["Data Reclamação Arquivada"] < df["Data Reclamação Baixada"])
]

print("Registros com arquivamento anterior à baixa:", len(inconsistencias_datas))

Registros com arquivamento anterior à baixa: 8

In [48]:
display(
    inconsistencias_datas[
        [
            "FA",
            "Status Reclamação",
            "Baixa da Reclamacao",
            "Data Cadastro Reclamação",
            "Data Reclamação Baixada",
            "Data Reclamação Arquivada"
        ]
    ]
)

,FA,Status Reclamação,Baixa da Reclamacao,Data Cadastro Reclamação,Data Reclamação Baixada,Data Reclamação Arquivada
246,23-002.001.25-0000029,Reclamação arquivada,Fundamentada Atendida,2025-01-14 11:16:57,2025-03-06 11:57:28,2025-03-06 11:57:27
569,23-002.004.24-0044926,Reclamação arquivada,Fundamentada Atendida,2025-01-29 14:59:40,2025-03-31 14:23:29,2025-03-31 14:23:28
1301,23-002.001.25-0002195,Reclamação arquivada,Fundamentada Não Atendida,2025-03-10 12:36:59,2025-04-25 11:01:04,2025-04-25 11:01:03
2216,23-002.004.25-0004784,Reclamação arquivada,Não Fundamentada/Encerrada,2025-04-30 15:12:33,2025-06-26 13:03:51,2025-06-26 13:03:50
3222,23-002.004.25-0009516,Reclamação arquivada,Não Fundamentada/Encerrada,2025-06-16 16:03:37,2025-08-12 11:37:48,2025-08-12 11:37:47
4310,23-002.001.25-0012229,Reclamação arquivada,Não Fundamentada/Encerrada,2025-08-06 10:02:12,2025-09-04 10:13:14,2025-09-04 10:13:13
5219,23-002.001.25-0013518,Reclamação arquivada,Não Fundamentada/Encerrada,2025-09-30 10:32:50,2025-11-03 11:05:14,2025-11-03 11:05:13
5244,23-002.006.25-0014050,Reclamação arquivada,Fundamentada Não Atendida,2025-10-01 09:06:49,2025-11-06 09:36:29,2025-11-06 09:36:28

In [49]:
data_atual = pd.Timestamp("2026-09-16")

for coluna in colunas_data:
    futuras = (df[coluna] > data_atual).sum()
    print(f"{coluna}: {futuras} datas futuras")

Data Cadastro Reclamação: 0 datas futuras
Data Reclamação Baixada: 0 datas futuras
Data Reclamação Arquivada: 0 datas futuras

In [50]:
casos_status_datas = df[
    (df["Status Reclamação"] == "Reclamação em Andamento") &
    (
        df["Data Reclamação Baixada"].notna() |
        df["Data Reclamação Arquivada"].notna()
    )
]

print(
    "Reclamações em andamento com data de baixa ou arquivamento:",
    len(casos_status_datas)
)

display(
    casos_status_datas[
        [
            "FA",
            "Status Reclamação",
            "Baixa da Reclamacao",
            "Data Reclamação Baixada",
            "Data Reclamação Arquivada"
        ]
    ].head(20)
)

Reclamações em andamento com data de baixa ou arquivamento: 0

Empty DataFrame
Columns: [FA, Status Reclamação, Baixa da Reclamacao, Data Reclamação Baixada, Data Reclamação Arquivada]
Index: []

In [51]:
baixa_sem_arquivamento = df[
    df["Data Reclamação Baixada"].notna() &
    df["Data Reclamação Arquivada"].isna()
]

arquivamento_sem_baixa = df[
    df["Data Reclamação Arquivada"].notna() &
    df["Data Reclamação Baixada"].isna()
]

print("Com baixa, mas sem arquivamento:", len(baixa_sem_arquivamento))
print("Com arquivamento, mas sem baixa:", len(arquivamento_sem_baixa))

Com baixa, mas sem arquivamento: 0
Com arquivamento, mas sem baixa: 0

In [52]:
print("Valores da coluna Área:")
print(df["Área"].unique())

Valores da coluna Área:
['Produtos' 'Assuntos Financeiros' 'Serviços Essenciais' 'Saúde'
 'Serviços Privados' 'Alimentos' 'Habitação']

In [53]:
print("Valores da coluna Tipo de Atendimento:")
print(df["Tipo de Atendimento"].unique())

Valores da coluna Tipo de Atendimento:
['Retorno da CIP' 'Abertura Direta da Reclamação'
 'Encaminhamento a Fiscalização']

In [54]:
print("Valores da coluna Status Reclamação:")
print(df["Status Reclamação"].unique())

Valores da coluna Status Reclamação:
['Reclamação arquivada' 'Reclamação em Andamento']

In [55]:
print("Valores da coluna Baixa da Reclamacao:")
print(df["Baixa da Reclamacao"].unique())

Valores da coluna Baixa da Reclamacao:
['Fundamentada Atendida' 'Fundamentada Não Atendida'
 'Não Fundamentada/Encerrada' 'Pendente' 'Consulta Fornecida']

In [56]:
print("Valores da coluna Unidade de Atendimento:")
print(df["Unidade de Atendimento"].unique())

Valores da coluna Unidade de Atendimento:
['Procon Fortaleza' 'Procon Fortaleza Núcleo Vapt Vupt Messejana'
 'Procon Fortaleza Núcleo Vapt Vupt Antônio Bezerra'
 'Procon Fortaleza Núcleo Vapt Vupt Rio Mar Papicu'
 'Procon Fortaleza Núcleo Vapt Vupt Centro'
 'Procon Fortaleza - Núcleo Regional 6'
 'Procon Fortaleza - Núcleo Regional 5'
 'Procon Fortaleza - Núcleo Câmara Municipal'
 'Procon Fortaleza Audiência Virtual'
 'Procon Fortaleza Núcleo Vapt Vupt Parangaba']

In [57]:
print("Quantidade de assuntos diferentes:", df["Assunto"].nunique())

Quantidade de assuntos diferentes: 148

In [58]:
assuntos_originais = df["Assunto"].nunique()

assuntos_sem_espacos = (
    df["Assunto"]
    .astype(str)
    .str.strip()
    .nunique()
)

print("Assuntos originais:", assuntos_originais)
print("Assuntos após remover espaços externos:", assuntos_sem_espacos)

Assuntos originais: 148
Assuntos após remover espaços externos: 148

In [59]:
assuntos_minusculos = (
    df["Assunto"]
    .astype(str)
    .str.strip()
    .str.lower()
    .nunique()
)

print("Assuntos originais:", df["Assunto"].nunique())
print("Assuntos após padronizar maiúsculas/minúsculas:", assuntos_minusculos)

Assuntos originais: 148
Assuntos após padronizar maiúsculas/minúsculas: 147

In [60]:
assuntos_padronizados = (
    df["Assunto"]
    .astype(str)
    .str.strip()
    .str.lower()
)

duplicados = (
    df.assign(Assunto_Padronizado=assuntos_padronizados)
      .groupby("Assunto_Padronizado")["Assunto"]
      .unique()
)

duplicados = duplicados[duplicados.apply(len) > 1]

display(duplicados)

Assunto_Padronizado
cartões de descontos    [Cartões de descontos, CARTÕES DE DESCONTOS]
Name: Assunto, dtype: object

In [61]:
df["Assunto"] = df["Assunto"].replace(
    "CARTÕES DE DESCONTOS",
    "Cartões de descontos"
)

print("Quantidade de assuntos após a correção:", df["Assunto"].nunique())

Quantidade de assuntos após a correção: 147

In [62]:
print("Quantidade de problemas diferentes:", df["Problema"].nunique())

Quantidade de problemas diferentes: 136

In [63]:
problemas_originais = df["Problema"].nunique()

problemas_sem_espacos = (
    df["Problema"]
    .astype(str)
    .str.strip()
    .nunique()
)

print("Problemas originais:", problemas_originais)
print("Após remover espaços externos:", problemas_sem_espacos)

Problemas originais: 136
Após remover espaços externos: 136

In [64]:
problemas_minusculos = (
    df["Problema"]
    .astype(str)
    .str.strip()
    .str.lower()
    .nunique()
)

print("Problemas originais:", df["Problema"].nunique())
print("Após padronizar maiúsculas/minúsculas:", problemas_minusculos)

Problemas originais: 136
Após padronizar maiúsculas/minúsculas: 136

In [65]:
problemas_espacos_internos = (
    df["Problema"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .nunique()
)

print("Problemas originais:", df["Problema"].nunique())
print("Após normalizar espaços:", problemas_espacos_internos)

Problemas originais: 136
Após normalizar espaços: 136

In [66]:
print("Quantidade de FAs diferentes:", df["FA"].nunique())
print("Quantidade de registros:", len(df))

print("\nExemplos de FA:")
display(df["FA"].head(10))

Quantidade de FAs diferentes: 6806
Quantidade de registros: 6806

Exemplos de FA:

0    23-002.001.24-0043898
1    23-002.001.24-0043846
2    23-002.001.24-0043851
3    23-002.001.24-0043862
4    23-002.004.24-0043430
5    23-002.001.24-0043878
6    23-002.001.24-0043854
7    23-002.006.24-0043617
8    23-002.001.24-0040209
9    23-002.011.25-0000004
Name: FA, dtype: object

In [67]:
print("Quantidade de consumidores diferentes:", df["Consumidor"].nunique())
print("Quantidade de registros:", len(df))

print("\nValores vazios:")
print(df["Consumidor"].isna().sum())

Quantidade de consumidores diferentes: 5972
Quantidade de registros: 6806

Valores vazios:
0

In [68]:
consumidores_originais = df["Consumidor"].nunique()

consumidores_padronizados = (
    df["Consumidor"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .nunique()
)

print("Consumidores originais:", consumidores_originais)
print("Após normalização:", consumidores_padronizados)

Consumidores originais: 5972
Após normalização: 5971

In [69]:
consumidores_padronizados = (
    df["Consumidor"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

duplicados_consumidor = (
    df.assign(Consumidor_Padronizado=consumidores_padronizados)
      .groupby("Consumidor_Padronizado")["Consumidor"]
      .unique()
)

duplicados_consumidor = duplicados_consumidor[
    duplicados_consumidor.apply(len) > 1
]

display(duplicados_consumidor)

Consumidor_Padronizado
maria de fatima da silva    [MARIA DE FATIMA DA SILVA , MARIA DE FATIMA DA...
Name: Consumidor, dtype: object

In [70]:
valores_maria = duplicados_consumidor["maria de fatima da silva"]

for valor in valores_maria:
    print(repr(valor))

'MARIA DE FATIMA DA SILVA '
'MARIA DE FATIMA DA SILVA'

In [71]:
df["Consumidor"] = df["Consumidor"].str.strip()

print("Quantidade de consumidores após a correção:")
print(df["Consumidor"].nunique())

Quantidade de consumidores após a correção:
5971

In [72]:
unidades_originais = df["Unidade de Atendimento"].nunique()

unidades_padronizadas = (
    df["Unidade de Atendimento"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .nunique()
)

print("Unidades originais:", unidades_originais)
print("Após normalização:", unidades_padronizadas)

Unidades originais: 10
Após normalização: 10

In [73]:
assuntos_normalizados = (
    df["Assunto"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .nunique()
)

print("Quantidade atual de assuntos:", df["Assunto"].nunique())
print("Após normalização:", assuntos_normalizados)

Quantidade atual de assuntos: 147
Após normalização: 147

In [74]:
print(df.dtypes)

Unidade de Atendimento               object
FA                                   object
Tipo de Atendimento                  object
Status Reclamação                    object
Baixa da Reclamacao                  object
Área                                 object
Assunto                              object
Problema                             object
Consumidor                           object
Data Cadastro Reclamação     datetime64[ns]
Data Reclamação Baixada      datetime64[ns]
Data Reclamação Arquivada    datetime64[ns]
dtype: object

In [75]:
print("Valores ausentes por coluna:")
print(df.isna().sum())

Valores ausentes por coluna:
Unidade de Atendimento         0
FA                             0
Tipo de Atendimento            0
Status Reclamação              0
Baixa da Reclamacao            0
Área                           0
Assunto                        0
Problema                       0
Consumidor                     0
Data Cadastro Reclamação       0
Data Reclamação Baixada      353
Data Reclamação Arquivada    353
dtype: int64

In [76]:
print("Quantidade final de registros:", len(df))
print("Quantidade final de colunas:", len(df.columns))

Quantidade final de registros: 6806
Quantidade final de colunas: 12

# FASE 3 - LOAD

In [77]:
df.to_csv(
    "fundamentadas-atendidas-2025-tratado.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivo tratado criado com sucesso!")

Arquivo tratado criado com sucesso!

In [78]:
df_final = pd.read_csv(
    "fundamentadas-atendidas-2025-tratado.csv",
    encoding="utf-8-sig"
)

print("Registros carregados:", len(df_final))
print("Colunas carregadas:", len(df_final.columns))
print("\nColunas:")
print(df_final.columns.tolist())

Registros carregados: 6806
Colunas carregadas: 12

Colunas:
['Unidade de Atendimento', 'FA', 'Tipo de Atendimento', 'Status Reclamação', 'Baixa da Reclamacao', 'Área', 'Assunto', 'Problema', 'Consumidor', 'Data Cadastro Reclamação', 'Data Reclamação Baixada', 'Data Reclamação Arquivada']

In [79]:
print(df_final.dtypes)

Unidade de Atendimento       object
FA                           object
Tipo de Atendimento          object
Status Reclamação            object
Baixa da Reclamacao          object
Área                         object
Assunto                      object
Problema                     object
Consumidor                   object
Data Cadastro Reclamação     object
Data Reclamação Baixada      object
Data Reclamação Arquivada    object
dtype: object

In [80]:
colunas_data_final = [
    "Data Cadastro Reclamação",
    "Data Reclamação Baixada",
    "Data Reclamação Arquivada"
]

for coluna in colunas_data_final:
    df_final[coluna] = pd.to_datetime(
        df_final[coluna],
        format="%Y-%m-%d %H:%M:%S",
        errors="coerce"
    )

print(df_final.dtypes)

Unidade de Atendimento               object
FA                                   object
Tipo de Atendimento                  object
Status Reclamação                    object
Baixa da Reclamacao                  object
Área                                 object
Assunto                              object
Problema                             object
Consumidor                           object
Data Cadastro Reclamação     datetime64[ns]
Data Reclamação Baixada      datetime64[ns]
Data Reclamação Arquivada    datetime64[ns]
dtype: object

In [81]:
print("Valores ausentes na base final:")
print(df_final.isna().sum())

print("\nQuantidade de registros:", len(df_final))
print("Quantidade de colunas:", len(df_final.columns))

Valores ausentes na base final:
Unidade de Atendimento         0
FA                             0
Tipo de Atendimento            0
Status Reclamação              0
Baixa da Reclamacao            0
Área                           0
Assunto                        0
Problema                       0
Consumidor                     0
Data Cadastro Reclamação       0
Data Reclamação Baixada      353
Data Reclamação Arquivada    353
dtype: int64

Quantidade de registros: 6806
Quantidade de colunas: 12

In [84]:
df_final.to_csv(
    "fundamentadas-atendidas-2025-tratado-excel.csv",
    index=False,
    encoding="utf-8-sig",
    sep=";"
)

print("Arquivo para Excel criado com sucesso!")

Arquivo para Excel criado com sucesso!

In [86]:
from google.colab import files

files.download("fundamentadas-atendidas-2025-tratado-excel.csv")